Aplikacija/Algebra/Controllers/PredbiljezbaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Algebra.Models;

namespace Algebra.Controllers
{
    public class PredbiljezbaController : Controller
    {
        private AlgebraEntities db = new AlgebraEntities();

        // GET: Predbiljezba
        public ActionResult Index(string searching)
        {
            return View(db.Seminar.Where(x => x.Naziv.Contains(searching) || searching == null).ToList());
        }

        // GET: Predbiljezba/Create
        public ActionResult Create()
        {
            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv");
            return View();
        }

        // POST: Predbiljezbe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPredbiljezba,Datum,Ime,Prezime,Adresa,Email,Telefon,IdSeminar,Status")] Predbiljezba predbiljezba)
        {
            if (ModelState.IsValid)
            {
                predbiljezba.Datum = DateTime.Now;
                db.Predbiljezba.Add(predbiljezba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv", predbiljezba.IdSeminar);
            return View(predbiljezba);
        }
    }
}

Aplikacija/Algebra/Controllers/PredbiljezbeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Algebra.Models;

namespace Algebra.Controllers
{
    public class PredbiljezbeController : Controller
    {
        private AlgebraEntities db = new AlgebraEntities();

        // GET: Predbiljezbe
        public ActionResult Index(string searching)
        {
            var predbiljezbas = db.Predbiljezba.Include(p => p.Seminar);
            return View(predbiljezbas.Where(x => x.Ime.Contains(searching) || searching == null).ToList());
        }

        // GET: Predbiljezbe/Create
        public ActionResult Create()
        {
            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv");
            return View();
        }

        // POST: Predbiljezbe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPredbiljezba,Datum,Ime,Prezime,Adresa,Email,Telefon,IdSeminar,Status")] Predbiljezba predbiljezba)
        {
            if (ModelState.IsValid)
            {
                db.Predbiljezba.Add(predbiljezba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv", predbiljezba.IdSeminar);
            return View(predbiljezba);
        }

        // GET: Predbiljezbe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predbiljezba predbiljezba = db.Predbiljezba.Find(id);
            if (predbiljezba == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv", predbiljezba.IdSeminar);
            return View(predbiljezba);
        }

        // POST: Predbiljezbe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPredbiljezba,Datum,Ime,Prezime,Adresa,Email,Telefon,IdSeminar,Status")] Predbiljezba predbiljezba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(predbiljezba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdSeminar = new SelectList(db.Seminar, "IdSeminar", "Naziv", predbiljezba.IdSeminar);
            return View(predbiljezba);
        }

        // GET: Predbiljezbe/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predbiljezba predbiljezba = db.Predbiljezba.Find(id);
            if (predbiljezba == null)
            {
                return HttpNotFound();
            }
            return View(predbiljezba);
        }

        // POST: Predbiljezbe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Predbiljezba predbiljezba = db.Predbiljezba.Find(id);
            db.Predbiljezba.Remove(predbiljezba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aplikacija/Algebra/Controllers/SeminarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Algebra.Models;

namespace Algebra.Controllers
{
    public class SeminarController : Controller
    {
        private AlgebraEntities db = new AlgebraEntities();

        // GET: Seminar
        public ActionResult Index(string searching)
        {
            return View(db.Seminar.Where(x => x.Naziv.Contains(searching) || searching == null).ToList());
        }


        // GET: Seminar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Seminar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSeminar,Naziv,Opis,Datum,Predavac,Popunjen,Popunjeno")] Seminar seminar)
        {
            if (ModelState.IsValid)
            {
                db.Seminar.Add(seminar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seminar);
        }

        // GET: Seminar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seminar seminar = db.Seminar.Find(id);
            if (seminar == null)
            {
                return HttpNotFound();
            }
            return View(seminar);
        }

        // POST: Seminar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSeminar,Naziv,Opis,Datum,Predavac,Popunjen")] Seminar seminar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seminar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seminar);
        }

        // GET: Seminar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seminar seminar = db.Seminar.Find(id);
            if (seminar == null)
            {
                return HttpNotFound();
            }
            return View(seminar);
        }

        // POST: Seminar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seminar seminar = db.Seminar.Find(id);
            db.Seminar.Remove(seminar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aplikacija/Algebra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["Korisnik"] != null)
                    {   
                        <li>@Html.ActionLink("Predbilježba", "Index", "Predbiljezba")</li>
                        <li>@Html.ActionLink("Seminari", "Index", "Seminar")</li>
                        <li>@Html.ActionLink("Predbilježbe", "Index", "Predbiljezbe")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Predbilježba", "Index", "Predbiljezba")</li>
                        <li>@Html.ActionLink("Seminari", "Index", "Login")</li>
                        <li>@Html.ActionLink("Predbilježbe", "Index", "Login")</li>
                    }
                </ul>
                <ul class="nav navbar-right" style="color:white">
                    @if (Session["Korisnik"] != null)
                    {
                        <h4 style="color:white">Bok @Session["Korisnik"]</h4>
                        @Html.ActionLink("Odjava", "Odjava", "Login")
                    }
                    else
                    {
                        @Html.Partial("_LoginPartial")
                    }
                </ul>                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Seminari</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>